added common/domain/users.java
swp2022/swp-server pull request #1
Opened 2022-04-27 08:05 UTC by LEEYEONGJAE1

added users.java

2022-04-27 08:10 UTC, sang-w0o requested changes
변수명이 snake case가 아니라 camel case 였으면 좋겠어요! 
Java에서는 이러이러한 컨벤션이 있어서 python과는 달리 camel case를 써요.

2022-04-27 08:10 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/users.java
> +    private Long user_id;
user_id가 mysql에서 auto_increment primary key 이니까 
```suggestion
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id",nullable = false)
    private Long user_id;
```

2022-04-27 08:10 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/users.java
> +    private LocalDateTime deleted_at;
```suggestion
    @Column(name="deleted_at", nullable = true)
    private LocalDateTime deleted_at;
```

2022-04-27 08:14 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/users.java
> +public class users {
Java에서 클래스명은 대문자로 하는게 컨벤션이에요!

클래스명을 users에서 `User` 로 바꾸는게 어떨까요?
```suggestion
@Entity
@Table(name = "users")
public class User {
```

2022-04-27 10:11 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/common/domain/Relationship.java
> +    private Long toUserId;
foreign key 2개를 primary key로 하려면 이렇게 하는거 맞나요?

2022-04-27 10:30 UTC, sang-w0o requested changes
1. 지금 `@ManyToOne`은 있지만, `@OneToMany`는 잘 보이지 않네요!!
  `@OneToMany`가 필요할 것 같은 상황만 코멘트 남겼으니, 확인 후 추가해주세요!!
  나머지는 이후에 필요할 때 수정하도록 하죠!

2. JPA Entity들이 있는 패키지가 `com.swp.common.domain`인데, 이걸 아래처럼 바꿔보면 어떨까요?

ex) `com.swp.common.domain.User.java` 를 `com.swp.user.domain.User.java`로,
`com.swp.common.domain.Board.java` 를 `com.swp.board.domain.Board.java`로요!

2022-04-27 10:30 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/users.java
> +public class users {
users(복수형)에서 user(단수형)로 한 이유는 이후에

```java
Users users = new Users(..);
```

처럼 코드가 나올텐데, 그럼 users 변수가 *사용자들* 인지, 아니면 *사용자* 인지 헷갈릴 수 있기 때문이에요.

2022-04-27 10:30 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/Board.java
> +    private Long userId;
`@ManyToOne`은 객체 참조 아닌가용??

```suggestion
    @ManyToOne
    @JoinColumn(name ="user_id",nullable = false)
    private User user;
```

2022-04-27 10:30 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/Board.java
> +    private Long userId;
아래 studyId도 마찬가지 입니다!

2022-04-27 10:30 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/Board.java
> +
불필요한 공백 같아요

2022-04-27 10:30 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/Comment.java
> +    private Long boardId;
```suggestion
    @ManyToOne
    @JoinColumn(name ="board_id",nullable = false)
    private Board board;
```

2022-04-27 10:30 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/Comment.java
> +    private Long boardId;
아래 userId도 마찬가지요!

2022-04-27 10:30 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/Board.java
> +
불필요한 공백!

2022-04-27 10:30 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/Study.java
> +    private Long userId;
```suggestion
    @ManyToOne
    @JoinColumn(name ="user_id",nullable=false)
    private User user;
```

2022-04-27 10:30 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/StudyLog.java
> +    private Long studyId;
```suggestion
    @ManyToOne
    @JoinColumn(name ="study_id",nullable = false)
    private Study study;
```

2022-04-27 10:30 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/StudyLog.java
> +    private double percentage;
이거 primitive type이면 안될거에요!~

```suggestion
    private Double percentage;
```

2022-04-27 10:30 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/Board.java
> +
`Board`에 `@OneToMany`가 추가되어야 할 것 같아요. 그래야 board로 해당 board의 모든 comment들을 가져올 수 있으니까요!!

2022-04-27 10:30 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/Relationship.java
> +    private Long toUserId;
아니요 이거 아니에요!! 구글링 해보시고, 다시 해보실래요??

2022-04-27 10:30 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/User.java
> +
여기에도 `@OneToMany`로 `Board`와의 관계 넣어주시면 좋을 것 같아요!

2022-04-27 10:31 UTC, sang-w0o commented on src/main/java/com/swp/common/domain/Relationship.java
> +    private Long toUserId;
[참고 링크](https://cjh5414.github.io/jpa-use-composite-key-to-foreign-key/)

2022-04-27 15:51 UTC, sang-w0o commented on src/main/java/com/swp/study/domain/Study.java
> +    @CreatedDate
여기도 `@CreatedDate`가 들어가는게 맞나요??

2022-04-27 15:51 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/RelationshipId.java
> +}
이 클래스가 이제 Primary Key를 나타내는 클래스가 되는데, JPA는 primary key를 `equals()`로 비교해서 [이 코드](https://github.com/sang-w0o/wantChu-Server/blob/master/src/main/java/com/wantchu/domain/favorite/CompositeFavoriteKeys.java) 처럼 `equals()` 메소드 오버라이딩 해줘야 해요!
```suggestion
@AllArgsConstructor
@NoArgsConstructor
public class RelationshipId implements Serializable {
    private Long fromUser;
    private Long toUser;
}
```

2022-04-27 15:51 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/User.java
> +    private List<Board> boardList = new ArrayList<Board>();
```suggestion
    private List<Board> boardList = new ArrayList<>();
```

2022-04-27 15:51 UTC, sang-w0o commented on src/main/java/com/swp/board/domain/Board.java
> +    private List<Comment> commentList = new ArrayList<Comment>();
```suggestion
    private List<Comment> commentList = new ArrayList<>();
```

2022-04-27 15:51 UTC, sang-w0o commented on src/main/resources/application.properties
> +spring.jpa.show-sql=true
지워주세요!

2022-04-27 23:35 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/study/domain/Study.java
> +    @CreatedDate
start_at datetime not null default now() 라서 맞는 것 같은데 아닌가요?

2022-04-27 23:35 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/domain/RelationshipId.java
> +}
코드가 안 보여요

2022-04-28 03:42 UTC, 0chil reviewed
의견과 같이 생각해봐야 할 내용을 남겼습니다

2022-04-28 03:42 UTC, 0chil commented on src/main/java/com/swp/study/domain/Study.java
> +    @CreatedDate
저도 맞다고 생각해요. 무엇이 마음에 걸리는지 궁금하네요!

2022-04-28 03:42 UTC, 0chil commented on src/main/java/com/swp/study/domain/Study.java
> +    @Column(name="end_at", nullable = false)
이런 부분은 어디다가 얘기해야할지 잘 모르겠네요.
스키마들을 정의할 때 end_at은 고려가 잘 못된 것 같습니다.
end_at 은 학습이 끝나기 전까지는 null 일 수 있기 때문에 nullable 해야 하는 것 아닐까요?

2022-04-28 04:06 UTC, 0chil reviewed
RelationshipId 의견 추가했습니다

2022-04-28 04:06 UTC, 0chil commented on src/main/java/com/swp/user/domain/RelationshipId.java
> +}
Relationship은 두 키를 모두 사용해 구분하는 복합 키라서 그에 맞게 equals()를 오버라이딩 해줘야겠네요.

[여기](https://docs.jboss.org/hibernate/stable/core.old/reference/en/html/persistent-classes-equalshashcode.html)를 참조해보세요!

```java
@AllArgsConstructor
@NoArgsConstructor
public class RelationshipId implements Serializable {
    private Long fromUser;
    private Long toUser;
    
    @Override
    public boolean equals(Object obj) {
        if(obj == null)
            return false;
        // Todo: this.fromUser, this.toUser <->  ((RelationshipId)obj).fromUser,((RelationshipId)obj).toUser를  모두 비교하는 메소드 작성
        ...
    }
}
```

2022-04-28 09:08 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/Relationship.java
> +    @JoinColumn(name="from_user_id",referencedColumnName = "user_id",nullable = false)
referencedColumnName 속성 지정 안해주면 어떻게 되나요??

2022-04-28 09:08 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/RelationshipId.java
> +}
override `equals()`

2022-04-28 12:38 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/study/domain/Study.java
> +    @Column(name="end_at", nullable = false)
학습 한 단위가 끝나고 나서 집중도랑 해서 db에 저장하는 방식 아니었나요?

2022-04-28 12:39 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/study/domain/Study.java
> +    @Column(name="end_at", nullable = false)
학습 하나가 끝나고 나서 넣을지 학습이 시작되면 넣을지 확실히 하는 게 좋을 것 같습니다.

2022-04-28 13:02 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/domain/Relationship.java
> +    @JoinColumn(name="from_user_id",referencedColumnName = "user_id",nullable = false)
상관 없는 것 같아요 지웠습니다

2022-05-02 14:18 UTC, merged