feat:게시글 기능 구현
swp2022/swp-server pull request #11
Opened 2022-05-17 05:54 UTC by LEEYEONGJAE1

구현한 내용:
- studyId 기반하여 
1. Board 생성
2. 수정(글을 쓴 user만 수정 가능)
3. 삭제(글을 쓴 user, Admin Role을 가지고 있어야만 삭제 가능)
- boardId로 글 가져오기
- userId로 내/타인 글 가져오기 (일단 페이지 구현 없이 List로 전부 가져오는 걸로 함)

study 임의로 생성하여 board 생성 테스트 해봤는데 잘 됨.
삭제/수정 모두 잘 됨. (타인 글 수정 불가 ok, admin은 테스트 못해봄)
user 삭제 시 study, board 모두 삭제 됨.

2022-05-17 07:43 UTC, 0chil requested changes
👍 따봉입니다
몇가지 신경 쓸 점이 있어요. 그리고 스페이스바 신경 좀 써주세요🥲
`Option+Command+L` 하시면 IDE가 포맷팅을 해줄거에요.

2022-05-17 07:43 UTC, 0chil commented on src/main/java/com/swp/board/controller/BoardController.java
> +
```java
@RequestMapping("/v1/board")
@RestController
public class BoardController {
    private final BoardService boardService;
}
```
이렇게 하시면 RequestMapping 의 `/v1/board/` 반복을 피할 수 있겠네요.

2022-05-17 07:43 UTC, 0chil commented on src/main/java/com/swp/board/domain/BoardService.java
> +                .getPrincipal();
우리 userDetails는 컨트롤러에서 받고, Service로 넘겨주는건 어떨까요?
서비스에는 서비스 로직**만** 들어있으면 좋을것 같아요.

```java
void someControllerMethod(){
    JwtUserDetails userDetails = (JwtUserDetails) SecurityContextHolder.getContext()
        .getAuthentication()
        .getPrincipal();
    boardService.createBoard(userDetails, boardCreateRequestDto);
}
```

```suggestion
    @Transactional
    public void createBoard(JwtUserDetails userDetails, BoardCreateRequestDto boardCreateRequestDto){
        
```

2022-05-17 07:43 UTC, 0chil commented on src/main/java/com/swp/board/domain/BoardService.java
> +        Board updatedBoard=boardRepository.findById(boardUpdateRequestDto.getBoardId())
변수 명이 `updatedBoard`라면 이미 업데이트 된 보드인데 의미 상 잘 안맞는것 같네요.
그냥 `board`로 하는 편이 좀 더 명확할 것 같습니다.

2022-05-17 07:43 UTC, 0chil commented on src/main/java/com/swp/board/dto/BoardResponseDto.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "Asia/Seoul")
이거 꼭 필요한 건가요? 필요하다면 원래 사용하던 응답과 형식을 맞춰주었으면 합니다. 지금 패턴은 조금 달라요.
```java
@Getter
@Builder
public class ErrorResponseDto {
    @JsonFormat(
            shape = JsonFormat.Shape.STRING,
            pattern = "yyyy-MM-dd HH:mm:ss",
            locale = "Asia/Seoul"
    )
    private LocalDateTime timestamp;
    ...
}
```

2022-05-17 11:10 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/board/dto/BoardResponseDto.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "Asia/Seoul")
저렇게 안 하면 
![image](https://user-images.githubusercontent.com/41511949/168797781-d4e46e01-7e09-414e-8486-34be4d7cc681.png)
이렇게 나와서 해 주는게 맞을 거 같아요. 말씀하신 format 으로 변경할게요

2022-05-17 11:10 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/board/domain/BoardService.java
> +        Board updatedBoard=boardRepository.findById(boardUpdateRequestDto.getBoardId())
그렇게 보일 수도 있겠네요. 수정하겠습니다.

2022-05-17 11:15 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/board/controller/BoardController.java
> +
네 그럼 BoardController에서는 저렇게 해서  Board 관련만 처리하도록 하고, Comment할 때는 컨트롤러 따로 또 만들어서 하도록 해야겠네요.

2022-05-17 11:25 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/board/domain/BoardService.java
> +                .getPrincipal();
네 그렇게 하는 게 좋을 것 같네요. Relationship에 있는 거는 이거 merge 하고 나중에 따로 할게요

2022-05-17 11:29 UTC, LEEYEONGJAE1 commented
> 👍 따봉입니다 몇가지 신경 쓸 점이 있어요. 그리고 스페이스바 신경 좀 써주세요🥲 `Option+Command+L` 하시면 IDE가 포맷팅을 해줄거에요.

이런 기능이 있는 지 몰랐네요. 감사합니다.

2022-05-17 11:43 UTC, sang-w0o requested changes

2022-05-17 11:43 UTC, sang-w0o commented on src/main/java/com/swp/board/controller/BoardController.java
> +    @ResponseStatus(HttpStatus.OK)
기본 http status code가 200이라 이 부분은 생략 가능해요!

2022-05-17 11:43 UTC, sang-w0o commented on src/main/java/com/swp/board/controller/BoardController.java
> +    public void createBoard(@RequestBody BoardCreateRequestDto boardCreateRequestDto) {
클라이언트에서 게시글 생성 이후에 어떻게 처리할 지는 모르겠지만, 생성된 게시글로 이동시키는 등의 다양한 경우에서 board_id가 필요해요. 따라서 `BoardCreateResponseDto`를 만들어서 반환하는건 어떨까요?

2022-05-17 11:43 UTC, sang-w0o commented on src/main/java/com/swp/board/controller/BoardController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
204는 주로 delete가 정상 처리되었을 때 사용해요. put 의 경우에는 200으로 두면 적절해요.

2022-05-17 11:43 UTC, sang-w0o commented on src/main/java/com/swp/board/domain/Board.java
> +		this.content=content;
code format

2022-05-17 11:43 UTC, sang-w0o commented on src/main/java/com/swp/board/domain/Board.java
> +		this.content=content;
code format

2022-05-17 11:43 UTC, sang-w0o commented on src/main/java/com/swp/board/domain/BoardRepository.java
> +
`@Repository` 추가

2022-05-17 11:43 UTC, sang-w0o commented on src/main/java/com/swp/board/domain/BoardService.java
> +            boardRepository.save(board);
`@Transactional`이 적용된 메소드 내에서는 `save()`를 명시적으로 호출해주지 않아도 메소드가 끝나면 자동으로 entity의 변경 사항이 database에 commit돼요!

2022-05-17 11:43 UTC, sang-w0o commented on src/main/java/com/swp/board/domain/BoardService.java
> +            throw new BoardForbiddenException("글을 수정할 권한이 없습니다.");
```suggestion
            throw new BoardForbiddenException("글을 삭제할 권한이 없습니다.");
```

2022-05-17 11:43 UTC, sang-w0o commented on src/main/java/com/swp/board/domain/BoardService.java
> +    }
아래 stream에서도 그렇고 `BoardResponseDto.builder()...build()`가 반복되는데, 이를 `BoardResponseDto`에 public static method로 만들어서 아래처럼 간략하게 사용하도록 하면 어떨까요?

```suggestion
        return BoardResponseDto.from(board);
    }
```

2022-05-17 11:43 UTC, sang-w0o commented on src/main/java/com/swp/board/controller/BoardController.java
> +    public void deleteBoard(@RequestBody BoardDeleteRequestDto boardDeleteRequestDto) {
이거는 왜 boardId를 path variable로 받지 않고 request body로 보내도록 하셨나요??

2022-05-17 11:43 UTC, sang-w0o commented on src/main/java/com/swp/board/dto/BoardResponseDto.java
> +public class BoardResponseDto {
board id는 무조건 필요하겠네요!

2022-05-17 11:43 UTC, sang-w0o commented on src/main/java/com/swp/study/domain/StudyRepository.java
> +
`@Repository`

2022-05-17 12:12 UTC, 0chil commented on src/main/java/com/swp/board/domain/BoardService.java
> +    }
@sang-w0o 오 저도 이게 좋을 것 같습니다. `.of()`는 어떨까요?

2022-05-17 12:50 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/board/domain/BoardService.java
> +            throw new BoardForbiddenException("글을 수정할 권한이 없습니다.");
복붙하다가 실수했네요. 수정하겠습니다.

2022-05-17 12:51 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/board/domain/BoardService.java
> +    }
좋은 것 같습니다. 그렇게 수정할게요

2022-05-17 12:53 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/board/controller/BoardController.java
> +    public void deleteBoard(@RequestBody BoardDeleteRequestDto boardDeleteRequestDto) {
create와 update에서 dto로 처리해서 비슷하게 하려고 저렇게 했었는데, 다른 것들이랑 다르게 boardId만 받으면 되니까 그게 더 나은 것 같네요. 수정하겠습니다.

2022-05-17 12:53 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/board/dto/BoardResponseDto.java
> +public class BoardResponseDto {
넵

2022-05-17 12:54 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/study/domain/StudyRepository.java
> +
넵

2022-05-17 12:56 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/board/controller/BoardController.java
> +    public void createBoard(@RequestBody BoardCreateRequestDto boardCreateRequestDto) {
좋은 것 같습니다. 그렇게 할게요

2022-05-17 12:56 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/board/controller/BoardController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
넵

2022-05-17 13:17 UTC, sang-w0o commented on src/main/java/com/swp/board/domain/BoardService.java
> +    }
`of()`는 `LocalDateTime`을 예로 들자면 새로운 객체를 만들어내기 위해 필요한 **값** 들을 인자로 전달받아 만들어주는데, 이 경우에는 다른 **객체** *로부터* 만들어지는 거라 `from()`이 낫다고 생각해요. 물론 주관적인 생각입니당

2022-05-17 13:19 UTC, 0chil commented on src/main/java/com/swp/board/domain/BoardService.java
> +                .getPrincipal();
이건 제가 조금 더 고민을 해봤는데, 아예 **DTO**를 사용해서 처리하는 편이 나을 것 같네요.
지금 상태로는 나중에 인증 방식을 바꾸게 된다면 (~~그렇지는 않지만~~) 서비스를 전부다 건드려야 합니다.
나중에 같이 리팩터링 하면서 (~~할 시간이 있을지는...~~ ) 인증된 유저를 가져오는 방식부터 바꿔야 할 것으로 보입니다.
일단은 통일만 해놓는 것으로 합시다.

2022-05-17 13:20 UTC, sang-w0o commented on src/main/java/com/swp/board/controller/BoardController.java
> +                .getPrincipal();
요것도 보통 request uri에 boardId는 넣고 content만 request body로 받는 식으로 처리되긴 해요.
아래 delete mapping과 같은 맥락이라고 봐주시면 돼요

2022-05-17 14:05 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/board/controller/BoardController.java
> +                .getPrincipal();
넵 그렇게 바꿀게요

2022-05-17 14:09 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/board/domain/BoardService.java
> +    }
다시 from으로 바꿀게요 그러면

2022-05-17 14:11 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/board/domain/BoardService.java
> +                .getPrincipal();
넵

2022-05-17 14:21 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/controller/RelationshipController.java
> +                .getPrincipal();
@0chil 님이 제안하셔서 Relationship도 Board와 같이 변경했습니다.

2022-05-17 14:21 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/controller/RelationshipController.java
> +                .getPrincipal();
Relationship도 Board와 같이 변경

2022-05-17 14:53 UTC, 0chil commented on src/main/java/com/swp/user/controller/RelationshipController.java
> +                .getPrincipal();
@LEEYEONGJAE1 영재님 이건 다른 브랜치에서 작업합시다! 너무 커져요!

2022-05-17 14:54 UTC, 0chil commented on src/main/java/com/swp/user/controller/RelationshipController.java
> +                .getPrincipal();
@LEEYEONGJAE1 영재님 이건 다른 브랜치에서 작업합시다! 너무 커져요!

2022-05-17 15:09 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/controller/RelationshipController.java
> +                .getPrincipal();
네 되돌릴게요

2022-05-18 07:41 UTC, sang-w0o approved these changes

2022-05-18 07:41 UTC, merged

2022-05-18 07:41 UTC, 0chil approved these changes