feat: 카카오 로그인
swp2022/swp-server pull request #2
Opened 2022-05-04 07:50 UTC by 0chil

OAuth 부분만 구현하였습니다.
JWT에 의한 인가가 남아있습니다.

2022-05-04 08:05 UTC, sang-w0o requested changes

2022-05-04 08:05 UTC, sang-w0o commented on src/main/java/com/swp/board/domain/Board.java
> +import javax.persistence.Table;
import를 왜 `*` 처리 안하고, 따로 따로 명시하셨나요??

2022-05-04 08:05 UTC, sang-w0o commented on src/main/java/com/swp/config/SecurityConfig.java
> +	}*/
주석은 제거해주세요!!

2022-05-04 08:05 UTC, sang-w0o commented on src/main/java/com/swp/oauth/OAuth2SuccessHandler.java
> +		System.out.println("oAuth2User = " + oAuth2User);
이런 sout 도 지워주세요!!

2022-05-04 08:05 UTC, sang-w0o commented on src/main/java/com/swp/oauth/OAuth2SuccessHandler.java
> +@Component
이 어노테이션은 왜 붙어 있는 건가요??

2022-05-04 08:05 UTC, sang-w0o commented on src/main/java/com/swp/oauth/ThirdPartyOAuth2Provider.java
> +	public abstract ClientRegistration.Builder getBuilder(String registrationId);
요건 모에요??

2022-05-04 08:05 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/User.java
> +	private String provider;
카카오 로그인 외에 다른 oauth provider를 사용할 것을 고려해 이걸 column으로 빼낸 건가요?

2022-05-04 08:05 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Integer> {
`JpaRepository`에도 `@Repository` 어노테이션이 적용되어 있는데, 그래도 이 인터페이스가 레포지토리 역할을 한다는 느낌을 주기 위해 `@Repository`를 적용해주는게 어떨까요??

2022-05-04 08:05 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/UserService.java
> +	void getUserInfo();
메소드 선언 사이에 개행을 두줄씩 한 이유가 궁금해요!

2022-05-04 08:05 UTC, sang-w0o commented on src/main/java/com/swp/user/dto/UserDto.java
> +	@ReadOnlyProperty
이 `@ReadOnlyProperty`는 어떤 역할을 하는 어노테이션 인가요??

2022-05-04 08:05 UTC, sang-w0o commented on src/main/java/com/swp/user/dto/UserDto.java
> +	@Column(nullable = false, unique = true)
`@Column`은 spring validation것이 아니라 spring data 꺼라서 여기선 아무런 의미가 없어요!
아마 `@NotNull`을 쓰려고 하셨던 것 같아요~!

2022-05-04 08:05 UTC, sang-w0o commented on src/main/resources/application.yml
> +jwt.Secret: '${JWT_SECRET}'
요기는 왜 `''`로 묶여 있나요??

2022-05-04 08:05 UTC, sang-w0o commented on src/main/java/com/swp/oauth/dto/KakaoOAuth2UserInfo.java
> +		return (String)((Map<String, Object>)attributes.get("profile")).get("nickname");
String으로 casting하기 보단, `toString()`을 호출하는건 어떻게 생각하시나요??

2022-05-04 08:10 UTC, 0chil commented on src/main/java/com/swp/board/domain/Board.java
> +import javax.persistence.Table;
자동 완성에 의해서 임포트가 많아졌습니다. 이건 정리하도록 할게요

2022-05-04 08:16 UTC, 0chil commented on src/main/java/com/swp/oauth/ThirdPartyOAuth2Provider.java
> +	public abstract ClientRegistration.Builder getBuilder(String registrationId);
스프링 OAuth2-client에서 Google, Facebook과 같은 잘 알려진 Provider에 대해서는 사전에 정의된 정보를 제공합니다.

Enum Class _org.springframework.security.config.oauth2.client.CommonOAuth2Provider_ 
```java
public enum CommonOAuth2Provider {

	GOOGLE {

		@Override
		public Builder getBuilder(String registrationId) {
			ClientRegistration.Builder builder = getBuilder(registrationId,
					ClientAuthenticationMethod.CLIENT_SECRET_BASIC, DEFAULT_REDIRECT_URL);
			builder.scope("openid", "profile", "email");
			builder.authorizationUri("https://accounts.google.com/o/oauth2/v2/auth");
			builder.tokenUri("https://www.googleapis.com/oauth2/v4/token");
			builder.jwkSetUri("https://www.googleapis.com/oauth2/v3/certs");
			builder.issuerUri("https://accounts.google.com");
			builder.userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo");
			builder.userNameAttributeName(IdTokenClaimNames.SUB);
			builder.clientName("Google");
			return builder;
		}

	},
```

 와 동일하게 동작하려고 코드를 복사해서 들어갔습니다. 이 부분도 지우도록 할게요.

2022-05-04 08:20 UTC, 0chil commented on src/main/java/com/swp/oauth/OAuth2SuccessHandler.java
> +@Component
이 컴포넌트에서 UserRepository를 생성자 주입받기 위해 들어가 있습니다. 현재는 관련 없으니 지우도록 하겠습니다!

2022-05-04 08:21 UTC, 0chil commented on src/main/java/com/swp/user/domain/UserService.java
> +	void getUserInfo();
이것도 마찬가지로 코드 리포맷 중 발생한 내용입니다. 원래 Java 코드 컨벤션은 다 붙이는지 궁금하네요!

2022-05-04 08:33 UTC, 0chil commented on src/main/java/com/swp/user/domain/User.java
> +	private String provider;
정답입니다 👍

2022-05-04 08:34 UTC, 0chil commented on src/main/java/com/swp/user/domain/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Integer> {
그게 더 좋겠네요. 👌

2022-05-04 08:39 UTC, 0chil commented on src/main/java/com/swp/user/dto/UserDto.java
> +	@ReadOnlyProperty
Presentation Layer에서 유저의 아이디를 변경할 일은 없기 때문에 명시적으로 읽기 전용이라고 표기하였습니다.
더 좋은 방법이 있거나, 의미가 없는 내용이라면 알려주세요!

2022-05-04 08:59 UTC, sang-w0o commented on src/main/java/com/swp/oauth/OAuth2SuccessHandler.java
> +@Component
아 주입 받으려면 아마 필요할 것 같은데, 확인 해보실래요??

2022-05-04 09:00 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/UserService.java
> +	void getUserInfo();
어 컨벤션에 따르는지는 모르겠지만, 여러 책이나 코드 예시들을 보면 붙이게 써놓긴 했어요!!

2022-05-04 09:00 UTC, sang-w0o commented on src/main/java/com/swp/user/dto/UserDto.java
> +	@ReadOnlyProperty
더 좋은 방법으로는 해당 프로퍼티를 final로 선언하는 방법이 있겠네요..!

2022-05-04 10:01 UTC, 0chil commented on src/main/java/com/swp/user/dto/UserDto.java
> +	@ReadOnlyProperty
잘 모르고 쓰는 것보다는 final 사용이 더 좋겠네요.

2022-05-04 11:31 UTC, 0chil commented on src/main/java/com/swp/user/dto/UserDto.java
> +	@ReadOnlyProperty
<img width="364" alt="image" src="https://user-images.githubusercontent.com/39221443/166673029-229d97ac-2699-49aa-99ab-46efecb336b9.png">
초기화되지 않았다고 오류가 뜹니다. 아마 이런 이유로 @ReadOnlyProperty Annotation을 쓰는 것 같긴 하네요.

2022-05-04 11:42 UTC, sang-w0o commented on src/main/java/com/swp/user/dto/UserDto.java
> +	@ReadOnlyProperty
저거는 필트 타입이 Integer여서 그래요!
int로 바꾸고, `private final int id;`로 해도 안되나용?

2022-05-09 05:33 UTC, sang-w0o commented on src/main/java/com/swp/board/domain/Board.java
> +import javax.persistence.Table;
확인해주세요!

2022-05-09 05:33 UTC, sang-w0o commented on src/main/java/com/swp/oauth/OAuth2SuccessHandler.java
> +@Component
요것도 확인해주세요!!

2022-05-09 05:33 UTC, sang-w0o commented on src/main/java/com/swp/config/SecurityConfig.java
> +			.antMatchers("/v1/**").hasRole(Role.USER.toString())
`Role.USER.toString()`이 맞나요, `Role.User.getValue()`가 맞나요??

2022-05-09 05:33 UTC, sang-w0o commented on src/main/java/com/swp/oauth/OAuth2SuccessHandler.java
> +	private static final String PROVIDER_KEY = "provider";
이 `PROVIDER_KEY`는 어떤 변수인가요??

2022-05-09 05:33 UTC, sang-w0o commented on src/main/java/com/swp/oauth/dto/KakaoOAuth2UserAttribute.java
> +}
여기서 null 처리해야 할건 따로 없겠죠..?

2022-05-09 05:33 UTC, sang-w0o commented on src/main/java/com/swp/oauth/dto/KakaoOAuth2UserAttribute.java
> +	private final Long id;
`User` 클래스의 id 타입이 `Long`이 아니라 `Integer`에요!!
여기에 `Long`으로 선언하신 이유가 있나요??

2022-05-09 05:33 UTC, sang-w0o commented on src/main/java/com/swp/user/controller/UserController.java
> +		return userService.getUser(userDetails.getProvider(), userDetails.getUsername());
이후에 사용자에 대한 작업을 처리할 때, 이 코드가 반복될 것처럼 보이네요!!
이후에 리팩토링하면서 고쳐봐요~!

2022-05-09 05:33 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/User.java
> +@Getter
`@Getter`는 필요한 필드에만 적용하는거 어때요??

2022-05-09 05:33 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/UserService.java
> +		System.out.println("user = " + user);
삭제 부탁해요!

2022-05-09 05:33 UTC, sang-w0o commented on src/main/resources/application.yml
> +      ddl-auto: validate
로컬에서 validate 하셨다면, none으로 바꿔주세요!

2022-05-09 07:48 UTC, sang-w0o commented on src/main/java/com/swp/oauth/OAuth2SuccessHandler.java
> +	private static final String PROVIDER_KEY = "provider";
OAuth provider(카카오)가 자신이 카카오임을 hashmap에 `["provider", "kakao"]`로 담아 반환합니다.

2022-05-09 07:52 UTC, sang-w0o commented on src/main/java/com/swp/oauth/dto/KakaoOAuth2UserAttribute.java
> +	private final Long id;
카카오 provider가 주는 id라 `Long`이 맞음

2022-05-09 08:00 UTC, merged