feat: nickname으로 유저 찾기
swp2022/swp-server pull request #25
Opened 2022-05-24 11:22 UTC by LEEYEONGJAE1

nickname으로 유저를 검색하는 기능입니다.

2022-05-25 04:23 UTC, 0chil requested changes

2022-05-25 04:23 UTC, 0chil commented on src/main/java/com/swp/user/controller/UserController.java
> +		return userService.getUserByNickname(nickname);
Annotation 둘 다 value = 은 빼주셔도 됩니다.

2022-05-25 04:23 UTC, 0chil commented on src/main/java/com/swp/user/domain/UserService.java
> +	}
전달이 잘못되었나 봅니다. 
단순히 닉네임으로 찾기가 아니라 검색 기능이었어요.`.contains()`로 하면 가능해보이는데, 어떤가요?

2022-05-25 04:37 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/domain/UserService.java
> +	}
네 수정해볼게요

2022-05-25 04:37 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/controller/UserController.java
> +		return userService.getUserByNickname(nickname);
넵

2022-05-25 08:09 UTC, sang-w0o approved these changes

2022-05-25 08:09 UTC, sang-w0o commented on src/main/java/com/swp/user/controller/UserController.java
> +	@ApiOperation(value = "유저 검색하기", notes="nickname에 검색 대상 문자열을 포함하는 유저 검색하기")
```suggestion
	@ApiOperation(value = "유저 검색하기", notes = "nickname에 검색 대상 문자열을 포함하는 유저 검색하기")
```

2022-05-25 14:07 UTC, 0chil commented on src/main/java/com/swp/user/domain/UserService.java
> +	}
```
daa
caaab
baaa
aa
a
```
가 있다고 할때,
`Contains()` -> aa를 검색하면 4개 `Like '%nickname%'`
`StartsWith()` -> aa를 검색하면 1개 `Like 'nickname%'`
저는 아래 것이 더 나아보이는데, 어떤가요?

2022-05-25 14:07 UTC, 0chil commented on src/main/java/com/swp/user/domain/UserRepository.java
> +	List<User> findByNicknameContains(String nickname);
검색도 페이징이 필요하지 않을까요?

2022-05-25 14:09 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/domain/UserService.java
> +	}
보통 검색을 그렇게 하니까 그게 더 좋은거 같아요

2022-05-25 14:09 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/domain/UserRepository.java
> +	List<User> findByNicknameContains(String nickname);
맞네요. 여기도 페이징 넣을게요

2022-05-26 07:40 UTC, LEEYEONGJAE1 commented
![image](https://user-images.githubusercontent.com/41511949/170441606-63b03ccc-90b8-47c5-a7c3-7119f8002bcc.png)
이렇게 되게끔 했는데 user response dto에 넣지 말고 그냥 다른 dto에 따로 할까요?

2022-05-26 09:26 UTC, 0chil approved these changes

2022-05-26 09:26 UTC, merged