Feat: 팔로워/팔로잉 기능 구현
swp2022/swp-server pull request #6
Opened 2022-05-13 08:09 UTC by LEEYEONGJAE1

2022-05-13 08:38 UTC, sang-w0o reviewed
고생 많으셨어요! 몇 가지 코멘트 및 궁금한 점만 남길게요.

1. `@RestController` 사용하기
2. 왜 `RelationshipController`는 request dto 그대로를 response로 반환하게 하셨나요?
3. `RelationshipRepository`에서 `coundByToUser`랑 `countByFromUser` 메소드는 안쓰이는데, 왜 선언되어 있나요?
4.

2022-05-13 08:38 UTC, sang-w0o commented on src/main/java/com/swp/ServerApplication.java
> +@SpringBootApplication()
이 괄호는 왜 추가된건가요??

2022-05-13 08:38 UTC, sang-w0o commented on src/main/java/com/swp/user/controller/RelationshipController.java
> +@Controller
여기에 `@Controller`를 `@RestController`로 바꾸면 response가 알아서 `application/json`으로 나가게 돼요.
따라서 `ResponseEntity`를 사용할 필요도 없어져요!

2022-05-13 08:38 UTC, sang-w0o commented on src/main/java/com/swp/user/controller/RelationshipController.java
> +    }
```suggestion
    @PostMapping(value = "/v1/relationship")
    public RelationshipResponseDto followUser(@RequestBody RelationshipRequestDto relationshipRequestDto){
        return relationshipService.createRelationship(relationshipRequestDto);
    }
```

`@RestController`를 적용하면 이렇게 바뀔 수 있겠네요!

2022-05-13 08:38 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/User.java
> +	@OneToMany(mappedBy = "fromUser",cascade = CascadeType.REMOVE)
Cascade는 어떤 이유로 지정해주신 건가요??

2022-05-13 08:46 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/ServerApplication.java
> +@SpringBootApplication()
어쩌다가 실수로 추가한것 같습니다. 지웠습니다.

2022-05-13 08:46 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/controller/RelationshipController.java
> +@Controller
네 확인했습니다.

2022-05-13 08:51 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/controller/RelationshipController.java
> +    }
>1번은 확인했습니다. 2번은 테스트 할 때 확인하려고 해 놓았는데 의미가 없으니 void로 바꾸고, 3번은 구현하다 쓸 수도 있을 것 같아서 추가했는데, 아직까지는 필요가 없네요 수정하겠습니다!

2022-05-13 08:56 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/domain/User.java
> +	@OneToMany(mappedBy = "fromUser",cascade = CascadeType.REMOVE)
관계를 삭제할 때 followerlist와 followinglist에서도 삭제하고 싶어서 저렇게 했는데, 안 써도 되거나 저럴 때 쓰는 것이 아닌가요??

2022-05-13 10:43 UTC, 0chil reviewed
수고하셨습니다.
생성자가 없는 문제가 있었구요.
그리고 전체적으로 띄어쓰기나 `,` 같은 포맷 관련한 부분을 정리해주시면 좋을것같네요.

2022-05-13 10:43 UTC, 0chil commented on src/main/java/com/swp/user/domain/Relationship.java
>  @Entity
Relationship은 Builder만 있고 Constructor가 없네요!
`@NoArgsConstructor` 를 삽입해주세요

2022-05-13 10:47 UTC, 0chil commented on src/main/java/com/swp/user/domain/User.java
> +	@OneToMany(mappedBy = "fromUser",cascade = CascadeType.REMOVE)
유저를 삭제할 때 유저와 관련된 관계를 삭제하려는 의도라면 잘 된 것 같지만, 관계 삭제할때 영향을 주려면 위치가 이곳이 아닌것 같습니다.

2022-05-13 11:35 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/domain/Relationship.java
>  @Entity
> 생성자 추가 했습니다. 그리고 띄어쓰기와 콤마 보이는 곳은 고쳤는데, 혹시 더 고칠 데가 있으면 말해주세요

2022-05-13 11:38 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/domain/User.java
> +	@OneToMany(mappedBy = "fromUser",cascade = CascadeType.REMOVE)
지웠습니다.

2022-05-13 12:53 UTC, 0chil commented on src/main/java/com/swp/user/domain/User.java
> +	@OneToMany(mappedBy = "fromUser",cascade = CascadeType.REMOVE)
@LEEYEONGJAE1 유저가 제거되면 관련된 관계는 사라져야 하니 오히려 잘 넣으신 것 같습니다.
지워달라는 말이 아니라 의도와 이유를 같이 얘기해보자는 말이에요. 원래 의도는 뭐였나요?

2022-05-13 13:41 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/domain/User.java
> +	@OneToMany(mappedBy = "fromUser",cascade = CascadeType.REMOVE)
@0chil 
유저가 삭제될 때도 생각을 했어야 했네요. 
원래 의도는 위에 적은 대로 관계 삭제할 때 사라지게 하려고 저렇게 했었던 거였습니다. 그러면 원래 의도대로 하려면 그냥 아무것도 안 적어도 되는 거였고, 유저가 삭제될 때를 고려하려 다시원래대로 추가하는 걸로 할까요?
만약에 유저 A가 삭제되면 자기를 팔로우하고 있는 유저들의 following 리스트에서 A의 정보를 삭제하고, 자기가 팔로우하고 있던 유저들의 follower 리스트에서 A의 정보를 삭제해야 할 것 같은데, 원래 적은대로 cascadeType.Remove를 해 주면 제가 의도한 대로 동작할까요?

2022-05-13 13:44 UTC, 0chil commented on src/main/java/com/swp/user/domain/User.java
> +	@OneToMany(mappedBy = "fromUser",cascade = CascadeType.REMOVE)
@LEEYEONGJAE1 네 그렇게 동작하겠네요. 말씀하신대로 처음 의도였다면 지우는게 맞았겠고, 유저 제거 시를 고려하면 Cascade를 지정하는 게 맞겠네요.

2022-05-13 14:11 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/domain/User.java
> +	@OneToMany(mappedBy = "fromUser",cascade = CascadeType.REMOVE)
넵 그럼 일단 cascade는 유지하는 걸로 하겠습니다

2022-05-13 16:06 UTC, 0chil approved these changes

2022-05-14 13:15 UTC, sang-w0o requested changes

2022-05-14 13:15 UTC, sang-w0o commented on src/main/java/com/swp/user/controller/RelationshipController.java
> +        relationshipService.createRelationship(relationshipRequestDto);
리소스가 생성됨을 표현하는 HTTP Status CREATED(201)을 주는 것은 어떨까요?
아래처럼 추가해주면 돼요!
```suggestion
    @PostMapping(value = "/v1/relationship")
    @ResponseStatus(HttpStatus.CREATED)
    public void followUser(@RequestBody RelationshipRequestDto relationshipRequestDto){
        relationshipService.createRelationship(relationshipRequestDto);
```

2022-05-14 13:15 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/RelationshipService.java
> +    }
이 메소드에서는 아래 3개의 쿼리가 나가는데요.

```sql
# 1
SELECT * FROM users WHERE provider = ? AND provider_id = ?;
# 2
SELECT * FROM users WHERE provider = ? AND provider_id = ?;
# 3
INSERT INTO relationships VALUES(?, ?, ?);
```

사용자 A가 B를 팔로우하려는 과정을 예로 들어볼게요.
1번 query가 수행될 때는 A가 있고, 2번 query가 수행될 때에 B가 있다고 해볼게요.
그런데 `relationships`에 INSERT query가 날라갈 때는 A 또는 B가 없을 수도 있어요.
따라서 `createRelationship()`의 모든 쿼리가 적용되기 전 상태로 rollback이 되어야 해요.
지금 상태로 이대로 가도 아무런 문제가 없긴 하겠지만, 여러 개의 query를 수행하는 함수는 
원활한 rollback 처리를 위해 `@Transactional` 어노테이션이 적용되어 있는게 좋아요!

2022-05-14 13:15 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/RelationshipService.java
> +    }
아래 `deleteRelationship()`도 마찬가지 입니당

2022-05-14 13:15 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/User.java
> +	@OneToMany(mappedBy = "fromUser",cascade = CascadeType.REMOVE)
이건 잘못된 것 같아요. 이대로라면 `User`가 삭제될 때 연관되어 있는 다른 `User`도 함께 삭제될 것 같은데요??

2022-05-14 13:56 UTC, 0chil commented on src/main/java/com/swp/user/domain/User.java
> +	@OneToMany(mappedBy = "fromUser",cascade = CascadeType.REMOVE)
[관련 글](https://catchdream.tistory.com/172)
이 문제에 관련한 글 입니다.
 더 정확히는 알아봐야겠지만 orphanRemoval = true를 써야하려나요?

그리고 사실 처음 영재님이 올린 상태에서 직접 유저를 제거하여 테스트 해봤었는데 상대 유저는 삭제되지 않았었습니다.
그런데 지금은 삭제 자체가 안되네요. 이건 좀 더 알아보는 게 좋겠습니다.

2022-05-14 16:50 UTC, 0chil commented on src/main/java/com/swp/user/domain/User.java
> +	@OneToMany(mappedBy = "fromUser",cascade = CascadeType.REMOVE)
@LEEYEONGJAE1 @sang-w0o 

# 사전 요약
둘 다 의도대로 동작하네요. 다시 부모로 전이가 일어나지 않습니다.
대신, 둘의 차이는 **부모 엔티티**를 삭제할 때가 아닌, 부모 엔티티에서 자식 엔티티를 **직접 삭제**할 때 생깁니다.

```java
User user1 = userRepository.findById(12345);
user1.getFollwingList().remove(0); 
// CascadeType.Remove의 경우 자식(Relationship)이 그대로 남고,
// orphanRemoval = true 의 경우 자식이 삭제됩니다.
```
- `orphanRemoval = true` 를 사용하는 것이 혹시 모를 오류를 막을 수 있겠네요.

MySQL DB를 써서인지 `@DataJpaTest`는 잘 안되고,
넣고 바로 삭제하는 테스트도 어려워서 `@Transactional`을 빼고 직접 진행했습니다.



# orphanRemoval = true 로 테스트
## 삭제 전
<img width="486" alt="스크린샷 2022-05-15 01 15 11" src="https://user-images.githubusercontent.com/39221443/168440066-18c1c860-2e41-46e8-b388-7c75efe730a4.png">
<img width="564" alt="스크린샷 2022-05-15 01 15 24" src="https://user-images.githubusercontent.com/39221443/168440071-e3f40a7a-4d09-44f9-982c-f3700ebe3ab0.png">

## 125번 유저 삭제 후
<img width="628" alt="스크린샷 2022-05-15 01 15 58" src="https://user-images.githubusercontent.com/39221443/168440089-0e0a708f-a817-4cc0-8385-16401b6a22c3.png">
<img width="552" alt="스크린샷 2022-05-15 01 16 07" src="https://user-images.githubusercontent.com/39221443/168440092-c59f899e-0ecf-450f-8f84-5b97e2670961.png">

## 143번 관계 삭제 후
<img width="493" alt="스크린샷 2022-05-15 01 33 37" src="https://user-images.githubusercontent.com/39221443/168440629-bcbcf00a-cc80-4f22-be65-83f303836af9.png">
<img width="577" alt="스크린샷 2022-05-15 01 33 59" src="https://user-images.githubusercontent.com/39221443/168440647-1b27ac60-fbc8-43ad-abb2-4730987df7c0.png">


## 결과
125번 유저 및 연관된 팔로우/팔로잉 관계가 제거되었고, 그와 연관된 다른 유저들은 영향받지 않았음 (유저로 전이 X)
그 반대로 Relationship을 제거해도 유저에 영향을 주지 않았음
-> 의도대로 동작함

# CascadeType.REMOVE 로 테스트
## 삭제 전
<img width="484" alt="스크린샷 2022-05-15 01 20 19" src="https://user-images.githubusercontent.com/39221443/168440222-6f281bbd-1bbc-4fbc-b74a-887e2d4b5865.png">
<img width="566" alt="스크린샷 2022-05-15 01 20 30" src="https://user-images.githubusercontent.com/39221443/168440230-3d94abe5-803f-4e58-a1c8-33c667962a65.png">

## 131번 유저 삭제 후

<img width="528" alt="스크린샷 2022-05-15 01 22 25" src="https://user-images.githubusercontent.com/39221443/168440297-5ebd5135-8774-4438-8994-006b8abffb73.png">
<img width="567" alt="스크린샷 2022-05-15 01 22 38" src="https://user-images.githubusercontent.com/39221443/168440306-2252842d-1fc4-408a-9701-56c35a27770a.png">

## 146번 관계 삭제 후
<img width="508" alt="스크린샷 2022-05-15 01 28 14" src="https://user-images.githubusercontent.com/39221443/168440476-60c45939-5e4c-4091-b212-7f474776ac36.png">

<img width="576" alt="스크린샷 2022-05-15 01 28 28" src="https://user-images.githubusercontent.com/39221443/168440484-1911d9f7-24da-46b6-aa46-1ee13494d2da.png">


## 결과
131번 유저 및 연관된 팔로잉/팔로우 관계가 제거되었고, 그와 연관된 다른 유저들은 영향받지 않았음 (유저로 전이 X)
그 반대로 Relationship을 제거해도 유저에 영향을 주지 않았음
-> 의도대로 동작함

2022-05-15 02:28 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/controller/RelationshipController.java
> +        relationshipService.createRelationship(relationshipRequestDto);
넵

2022-05-15 02:28 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/domain/RelationshipService.java
> +    }
넵 감사합니다

2022-05-15 02:41 UTC, LEEYEONGJAE1 commented on src/main/java/com/swp/user/domain/User.java
> +	@OneToMany(mappedBy = "fromUser",cascade = CascadeType.REMOVE)
그럼 relationship까지 삭제될 수 있도록 orphanRemoval=true까지 넣도록 하겠습니다. 테스트 감사합니다

2022-05-15 06:44 UTC, sang-w0o commented on src/main/java/com/swp/user/domain/User.java
> +	@OneToMany(mappedBy = "fromUser",cascade = CascadeType.REMOVE)
앞으로 API 개발 시에는 테스트 꼭 직접 해주세요~

2022-05-15 06:45 UTC, sang-w0o approved these changes

2022-05-15 06:45 UTC, sang-w0o commented on src/main/java/com/swp/user/controller/RelationshipController.java
> +    @DeleteMapping(value = "/v1/relationship")
이친구도 `@ResponseStatus(HttpStatus.NO_CONTENT)` 주는게 좋아 보이네요.
반영 후 merge 바로 해주세요!

2022-05-15 07:34 UTC, merged